anti-virus-function-app-SonarQube 10.4 (#19)
* Exclude from Code coverage because of Compiler Error CS0718: static types cannot be used as type arguments. Because a static type cannot be instantiated, it cannot be used as a generic argument in ConfigurationExtensions.ConfigureOptions()

* Upgraded Azure.Identity to version 1.12.0

* Suppress S1118 since SonarCloud is not aware that a class is to instantiated by DI and therefore it cannot be static.

* Resolved SonarQube issues & warnings after .net8 upgrade.

* Tidied up SubmissionStatusApiClientTests.cs

---------

Co-authored-by: Dat Tonthat (ext) <dat.tonthat.external@eviden.com>
Co-authored-by: Hardik Desai <hardikkumar.desai.external@eviden.com>