Exclude from Code coverage because of Compiler Error CS0718: static types cannot be used as type arguments. Because a static type cannot be instantiated, it cannot be used as a generic argument in ConfigurationExtensions.ConfigureOptions()